### ISSUE TITLE
param

### ISSUE THREAD

**Issue by shahirahasim** [arslanberk/Vulnarity#3]
hi. can i know why you have to put $Vparam? c

**Comment by arslanberk** [comment]
There is no web crawler in this example. That is why, we have to find a way to detect URL parameters to test. $Vparam is nonsense in URL, therefore I have decided to use it to find the URL parameter for testing. Purpose of this repository is to explain basics of SQL Injection vulnerability test. 
If you want to develop something you can use, then you should use a web crawler to discover all possible links, forms, and some required parameters for testing purpose.

**Comment by shahirahasim** [comment]
Oh i see. Thank you for your feedback. I just want to do the research. So mean here you are not using static code analysis or dynamic techniques for testing? I'm sorry this is my first time research about this.      On Thursday, November 15, 2018, 6:51:45 AM GMT+8, Berk Arslan <notifications@github.com> wrote:  
 
 
There is no web crawler in this example. That is why, we have to find a way to detect URL parameters to test. $Vparam is nonsense in URL, therefore I have decided to use it to find the URL parameter for testing. Purpose of this repository is to explain basics of SQL Injection vulnerability test.
If you want to develop something you can use, then you should use a web crawler to discover all possible links, forms, and some required parameters for testing purpose.

**Comment by arslanberk** [comment]
No I did not use such techniques. What it does is basically trying to send some malicious parameter values instead of $Vparam and analyze the response.
